name: WSL
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
defaults:
  run:
    shell: wsl-bash {0}
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: WSL POC
        run: cat /etc/debian_version
